name: vincenty-core

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags: [ '*' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          override: true
          components: clippy, rustfmt

      - name: Check
        run: cargo check --release

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: -- -W clippy::all

      - name: Run tests
        run: cargo test --release
